// Headless check of the calculator core against paper/results.md (run: node test.js)
const fs = require('fs');
const html = fs.readFileSync(__dirname + '/index.html', 'utf8');
const core = html.slice(html.indexOf('const gasdyn = (() => {'), html.indexOf('if (typeof module'));
const g = new Function(core + '; return gasdyn;')();
const mixText = html.slice(html.indexOf('let mixtures = ['), html.indexOf('];', html.indexOf('let mixtures = [')) + 2);
const mixtures = new Function(mixText + '; return mixtures;')();

// Reference values from paper/results.md (generated by paper/results_table.py)
const REF = {
  'H2/O2 stoich (phi=1)':   {D:3632, delta:12.64, pr:0.99426, M2:0.072},
  'H2/air stoich (phi=1)':  {D:1984, delta:6.58,  pr:0.99957, M2:0.020},
  'H2/air lean (phi=0.5)':  {D:1492, delta:4.41,  pr:0.99997, M2:0.006},
  'H2/air phi=1.5':         {D:2022, delta:6.02,  pr:0.99970, M2:0.017},
};
let fail = 0;
const check = (name, cond) => { if (!cond) { fail++; console.log('FAIL', name); } };
for (const r of mixtures) {
  const {gamma1:g1, gamma2:g2, p1, rho1:r1, q, u1, R2} = r;
  const cj = g.cjDetonation(g1,g2,p1,r1,q,R2);
  const d = g.combustionFromU1(g1,g2,p1,r1,q,u1,R2);
  check(r.mix+' CJ residual', g.residuals(g1,g2,p1,r1,cj.u1,q,cj.p2,cj.r2,cj.u2).max < 1e-12);
  check(r.mix+' CJ sonic', Math.abs(cj.u2*cj.u2 - g2*cj.p2/cj.r2)/(cj.u2*cj.u2) < 1e-12);
  check(r.mix+' deflagration residual', g.residuals(g1,g2,p1,r1,u1,q,d.p2,d.r2,d.u2).max < 1e-10);
  check(r.mix+' subsonic products', d.M2 < 1);
  check(r.mix+' both roots u2>u1', d.u2 > u1 && d.root2.u2 > u1);
  const ref = REF[r.mix];
  if (ref) {
    check(r.mix+' D_CJ', Math.abs(cj.u1 - ref.D) < 0.5);
    check(r.mix+' delta', Math.abs(d.delta - ref.delta) < 0.005);
    check(r.mix+' p2/p1', Math.abs(d.p2/p1 - ref.pr) < 5e-6);
    check(r.mix+' M2', Math.abs(d.M2 - ref.M2) < 5e-4);
  }
  const R = g.regime(g1,g2,p1,r1,q,R2,u1);
  check(r.mix+' regime weak_def', R.kind === 'weak_def');
  check(r.mix+' forbidden zone', g.regime(g1,g2,p1,r1,q,R2,(R.uDef+cj.D)/2).kind === 'forbidden');
  check(r.mix+' cj_det', g.regime(g1,g2,p1,r1,q,R2,cj.D).kind === 'cj_det');
  check(r.mix+' strong_det', g.regime(g1,g2,p1,r1,q,R2,cj.D*1.3).kind === 'strong_det');
}
check('shock guard M1<=1', g.normalShockFromU1(1.4,101325,1.225,293,200).ok === false);
check('shock guard pr<=1', g.normalShockFromPr(1.4,101325,1.225,293,0.9).ok === false);
const s = g.normalShockFromU1(1.4,101325,1.225,293,680);
check('shock p2/p1', Math.abs(s.p2/101325 - 4.4919) < 1e-3);
console.log(fail ? `${fail} check(s) failed` : 'all checks passed');
process.exit(fail ? 1 : 0);
